name: Continuous integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install gcc 11
      run: sudo apt-get install gcc-11 g++-11
    - name: install qt
      uses: jurplel/install-qt-action@v2.13.2
    - name: install opengl
      run: sudo apt-get install mesa-common-dev libglu1-mesa-dev ninja-build -y
    - name: cmake
      run: CC="gcc-11" CXX="g++-11" cmake -GNinja -DTESTS=OFF -DBENCHMARKS=OFF .
    - name: ninja 
      run: CC="gcc-11" CXX="g++-11" ninja
